import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "build" : ".";

/**
 * Stamp the source manifest with a dev-suffixed version for the test vault
 * so every build looks like a fresh version to Obsidian's plugin loader —
 * defeats stale-module caching during manual QA. Source manifest.json is
 * NEVER modified; the canonical version stays the GitHub release version.
 *
 * Format mirrors miyo-archivist + miyo-tomo-hashi:
 * `${baseVersion}-dev.${YYYYMMDD-HHmm}`, e.g. "0.0.0-dev.20260428-1620".
 * The `-dev.` is a semver pre-release identifier so it sorts BELOW the
 * canonical version — Obsidian and the Community Plugins manifest stay clean.
 */
function stampManifestForVault() {
	const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
	const baseVersion = manifest.version;
	const stamp = new Date()
		.toISOString()
		.slice(0, 16)
		.replace(/[-:]/g, "")
		.replace("T", "-");
	manifest.version = `${baseVersion}-dev.${stamp}`;
	return manifest;
}

// Copy plugin assets to build/ (production only) and into the in-repo test
// vault for manual QA. The vault deploy runs in BOTH dev (watch) and production
// builds — guarded only on the vault existing — so `npm run dev` keeps the
// vault live and Hot Reload reloads the plugin on every rebuild. CI builds have
// no vault, so the existsSync guard skips the deploy automatically.
//
// Do NOT symlink main.js/manifest.json into the vault: Electron's plugin loader
// does not follow symlinked plugin files reliably. We copy real files instead.
const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				mkdirSync("build", { recursive: true });
				copyFileSync("manifest.json", "build/manifest.json");
				copyFileSync("styles.css", "build/styles.css");
			}

			const VAULT_DIR = "test/Orbital/.obsidian";
			const VAULT_PLUGIN_DIR = `${VAULT_DIR}/plugins/orbital`;
			if (!existsSync(VAULT_DIR)) return;

			mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
			copyFileSync(`${outdir}/main.js`, `${VAULT_PLUGIN_DIR}/main.js`);
			if (existsSync("styles.css")) {
				copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
			}
			const stampedManifest = stampManifestForVault();
			writeFileSync(
				`${VAULT_PLUGIN_DIR}/manifest.json`,
				JSON.stringify(stampedManifest, null, "\t") + "\n",
				"utf8",
			);
			// Hot Reload only watches a plugin folder that contains `.git` or
			// `.hotreload`. The deployed folder has neither, so drop the marker
			// in to enable live reload on rebuild.
			if (!existsSync(`${VAULT_PLUGIN_DIR}/.hotreload`)) {
				writeFileSync(`${VAULT_PLUGIN_DIR}/.hotreload`, "", "utf8");
			}
			console.log(
				`[deploy] Plugin copied to ${VAULT_PLUGIN_DIR} (version: ${stampedManifest.version})`,
			);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	loader: {
		// Inline binary assets as base64 data URIs. The Obsidian Community
		// Plugins installer and BRAT both fetch only `main.js`, `manifest.json`,
		// and `styles.css` from a release — anything in a sibling `assets/`
		// folder is silently dropped. Inlining the hanko (and any other build-
		// time PNG) keeps it reachable on every install path.
		".png": "dataurl",
	},
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
